name: order-processing-system

networks:
  order-processing-system:
    driver: bridge

services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ./services/eureka-server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - order-processing-system

  centralized-config:
    container_name: centralized-config
    env_file:
      - .env.docker
    build:
      context: ./services/centralized-config
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - order-processing-system
    depends_on:
      - eureka-server

#  inventory:
#    container_name: inventory
#    build:
#      context: ./services/inventory
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "9091:9091"
#    networks:
#      - order-processing-system
#    depends_on:
#      - eureka-server
#      - centralized-config

  shop-app:
    container_name: shop-app
    env_file:
      - .env.docker
    build:
      context: ./services/shop-app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - order-processing-system
    depends_on:
      - eureka-server
      - centralized-config
