name: order-processing-system

networks:
  order-processing-system:
    driver: bridge

services:
  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    hostname: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  eureka-server:
    container_name: eureka-server
    build:
      context: ./services/eureka-server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - order-processing-system

  centralized-config:
    container_name: centralized-config
    env_file:
      - .env.docker
    build:
      context: ./services/centralized-config
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - order-processing-system
    depends_on:
      - eureka-server

  inventory:
    container_name: inventory
    env_file:
      - .env.docker
    build:
      context: ./services/inventory
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9091:9091"
    networks:
      - order-processing-system
    depends_on:
      - eureka-server
      - centralized-config
      - kafka

  shop-app:
    container_name: shop-app
    env_file:
      - .env.docker
    build:
      context: ./services/shop-app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - order-processing-system
    depends_on:
      - kafka
      - redis
      - eureka-server
      - centralized-config
