server:
  port: 8888

spring:
  application:
    name: centralized-config

  config:
    import: classpath:configs/commons.yaml

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nvhuu99/order-processing-system
          search-paths:
            - services/centralized-config/src/main/resources/configs
