order-processing-system:
  messaging:
    cart-update-requests:
      topic-name: cart-update-requests
      consumer-group-name: cart-manager.cart-update-requests

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh