order-processing-system:
  storages:
    cart-cache:
      prefix: "order-processing-system:carts:"
  messaging:
    cart-update-requests:
      topic-name: cart-update-requests
      consumer-group-name: cart-manager.cart-update-requests
  handlers:
    cart-update-requests:
      timeout-sec: 10

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh