server:
  port: 8082
  error:
    include-stacktrace: never
    include-message: always
logging:
  level:
    root: INFO                        # default: only INFO, WARN, ERROR
    org.springframework: WARN
    org.springframework.web: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: ERROR
    reactor.netty: WARN

spring:
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

  grpc:
    client:
      channels:
        inventory-service:
          address: ${INVENTORY_HOST:inventory}:${INVENTORY_GRPC_PORT:9091}
          plaintext: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}
    admin:
      auto-create: true
    listener:
      ack-mode: manual
    consumer:
      group-id: cart-manager.cart-update-requests
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer